FROM python:3.13-slim

# 작업 폴더 생성
WORKDIR /app

# requirements.txt 복사
COPY requirements.txt .

# 라이브러리 설치
RUN pip install --no-cache-dir -r requirements.txt

# 프로젝트 전체 복사
COPY . .


# start.sh 파일 권한 부여
# permission denied 에러 시 주석 처리 후 별도 실행
# ---------------------------------------------
RUN chmod +x start.sh


# start.sh - FastAPI 실행
# CMD ["./start.sh"]
CMD ["bash", "start.sh"]