# Node.js 22 공식 이미지 사용
FROM node:22

# 작업 폴더 생성
WORKDIR /app

# package.json 복사
COPY package*.json ./

# 라이브러리 설치
RUN npm install

# 프로젝트 전체 복사
COPY . .

# Vite 포트
EXPOSE 5173

# React 실행
CMD ["npm", "run", "dev", "--", "--host"]